/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const EditSettings = IDL.Record({
  'trimOut' : IDL.Nat,
  'mute' : IDL.Bool,
  'trimIn' : IDL.Nat,
  'playbackSpeed' : IDL.Float64,
});
export const Project = IDL.Record({
  'created' : Time,
  'name' : IDL.Text,
  'settings' : EditSettings,
  'updated' : Time,
});

export const idlService = IDL.Service({
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listProjectsView' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
      ['query'],
    ),
  'saveProject' : IDL.Func([IDL.Text, EditSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const EditSettings = IDL.Record({
    'trimOut' : IDL.Nat,
    'mute' : IDL.Bool,
    'trimIn' : IDL.Nat,
    'playbackSpeed' : IDL.Float64,
  });
  const Project = IDL.Record({
    'created' : Time,
    'name' : IDL.Text,
    'settings' : EditSettings,
    'updated' : Time,
  });
  
  return IDL.Service({
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listProjectsView' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
    'saveProject' : IDL.Func([IDL.Text, EditSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };